name: Recently played games
uses: lowlighter/metrics@latest
with:
  filename: metrics.plugin.steam.svg
  token: NOT_NEEDED
  base: ""
  plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
  plugin_steam: yes
  plugin_steam_user: "76561198062092975"
  plugin_steam_sections: recently-played
  plugin_steam_achievements_limit: 0
